<a href="https://colab.research.google.com/github/suakii/2013JuniorCamp/blob/master/AI_%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98_3_1_%EB%84%98%ED%8C%8C%EC%9D%B4(%EB%B0%95%EC%A2%85%ED%99%94_%EA%B9%80%EC%A2%85%ED%98%9C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ai 와 알고리즘 $\mathrm{III}$

학습목표:

    신경망 모델 설계의 이해

이론: 

    신경망 모델, 활성화 함수


실습: 

    파이썬을 이용한 간단한 신경망 모델 설계
    다양한 활성화 함수 이해 및 실습
    Numpy를 이용하녀 다차원 배열 및 행렬연산 실습





#Numpy
Numpy 패키지(모듈)은 파이썬으로 수행되는 수치 연산에서 대부분 사용이 되는 인기 있는 모듈이며, 인공지능 분야에서도 넘파이의 사용은 필수적이다. 넘파이는 벡터, 행렬, 다차원 데이터 타입의 연산을 편리하게 수행할 수 있도록 도와주며, 내부는 C와 Fortran으로 작성되어 있어 속도가 느리다는 파이썬의 단점을 보완해줄 수 있는 훌륭한 패키지다.

2019년 4월 10일 우리는 뉴스를 통해 최초의 블랙홀 이미지를 보게 되었다. 다음 그림은 넘파이 홈페이지에 있는 내용으로 블랙홀 이미지를 만들어 내기 위해 사용된 프로그램을 보여준다. 넘파이도 이미지를 만드는 작업에 사용된 것을 알 수 있다.
<p align="center"><img src="https://numpy.org/images/content_images/cs/bh_numpy_role.png" width="70%" height="70%"></p>

넘파이를 사용하기 위해서는 다음과 같이 모듈을 임포트 해준다. 넘파이는 보통 별칭으로 관례적으로 np라고 사용한다. 물론 
```
from numpy import *
```
이라는 문장을 통해서 사용할 수 도 있지만 대부분의 넘파이를 활용하는 코드에서는
```
import numpy as np
```
라고 작성한다.




In [ ]:
import numpy as np

넘파이가 제공하는 함수는 600개가 넘으며 이를 활용하여 보다 편리하게 행렬을 다루는 연산들을 수행할 수 있도록 해준다.

In [ ]:
len(dir(np))

620

## 벡터
Numpy이는 벡터와 행렬을 기본적으로 다루기에 벡터와 행렬에 대한 이해가 필요하다.
벡터는 크기와 방향을 갖는 양으로 정의가 된다. 크기가 n인 벡터는 n개의 원소를 가진 배열로 볼 수 있으며 다음과 같이 표시할 수 있다.
$$
\begin{align}
    y &= \begin{bmatrix}
           x_{1} \\
           x_{2} \\
           \vdots \\
           x_{m}
         \end{bmatrix}
  \end{align}	
$$
벡터의 경우에는 구성하는 원소의 순서가 의미가 있으며 서로 다른 순서는 다른 벡터로 취급한다.크기가 $n$인 모든 벡터의 집합을 $R^n$이라고 하며 $n$차원을 가진 공간을 의미한다. 
벡터의 형태에 따라 열벡터와 행벡터가 있으며, 필요한 경우 이를 자유롭게 사용할 수 있다.

$$\overrightarrow{A} = \{4,3\}$$

Numpy에서 벡터는 **np.array()** 함수를 통해서 표현이 된다. Numpy의 array는 같은 타입의 값들의 모임이며 인덱스를 통해 접근할 수 있다.

### 벡터 만들기
Numpy 에서는 다양한 방법으로 벡터를 만들 수 있다. 
다음은 np.array 와 리스트를 통해 배열을 만드는 것이다.

In [ ]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


또한, arange 함수를 통해 특정 구간의 값들을 가지는 벡터를 만들 수 있다.

In [ ]:
y = np.arange(10)
z = np.arange(3, 10)
print(y)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]


다음처럼 linspace 함수를 사용할 경우 시작과 끝을 포함하여 100개의 구간으로 이루어진 벡터를 정의할 수 있다.

In [ ]:
k = np.linspace(1, 10, 100)
print(k)


[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

### 벡터의 크기와 방향
벡터 $\overrightarrow{v} = (v_1,v_2)$ 의 크기는 다음과 같의 정의한다.

\begin{equation}\|\vec{v}\| = \sqrt{v_{1}\;^{2} + v_{2}\;^{2}}\end{equation}

다음 벡터 $V$의 크기는 
\begin{equation}\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}\end{equation}


\begin{equation}\|\vec{v}\| = \sqrt{2^{2} + 1^{2}}  = \sqrt{4 + 1} = \sqrt{5} \approx 2.24\end{equation}
이다.


In [ ]:
v = np.array([2, 1])
vMag = np.sqrt(v[0]**2 + v[1]**2)
print (vMag)

2.23606797749979


### 방향
원점과 벡터의 좌표를 연결한 형태로 나타낸 것을 위치벡터라고 하며 이때는 각을 다음과 같이 나타낼 수 있다.

\begin{equation}tan(\theta) = \frac{1}{2}\end{equation}
\begin{equation}\theta = tan^{-1} (0.5) \approx 26.57^{o}\end{equation}


In [ ]:
v = np.array([2,1])
vTan = v[1] / v[0]
print ('tan = ' + str(vTan))
vAtan = np.arctan(vTan)
# radian to degree
print('inverse-tan = ' + str(np.degrees(vAtan)))

tan = 0.5
inverse-tan = 26.56505117707799


### 벡터의 합
\begin{equation}\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}\end{equation}

\begin{equation}\vec{s} = \begin{bmatrix}-3 \\ 2 \end{bmatrix}\end{equation}
벡터의 합은 두 벡터의 같은 위치의 값 끼리 더해서 새로운 벡터를 만든다.

\begin{equation}\vec{z} = \vec{v}+\vec{s}\end{equation}

\begin{equation}\vec{z} = \begin{bmatrix}2 \\ 1 \end{bmatrix} + \begin{bmatrix}-3 \\ 2 \end{bmatrix}\end{equation}

\begin{equation}\vec{z} = \begin{bmatrix}2 \\ 1 \end{bmatrix} + \begin{bmatrix}-3 \\ 2 \end{bmatrix} = \begin{bmatrix}-1 \\ 3 \end{bmatrix}\end{equation}


In [ ]:
v = np.array([2,1])
s = np.array([-3,2])
z = v + s
print(z)

[-1  3]


### 벡터의 곱
벡터의 곱은 3가지로 연산할 수 있다.
- 스칼라 곱
- 내적
- 외적

In [ ]:
# 스칼라 곱
v = np.array([2,1])

w = 2 * v
print(w)

[4 2]


#### 내적
벡터의 내적은 같은 위치의 원소끼리 곱하고 더한 결과이며 이는 스칼라가 된다.
\begin{equation} \vec{v} \cdot \vec{s} = (v_{1} \cdot s_{1}) + (v_{2} \cdot s_{2}) ... + \; (v_{n} \cdot s_{n})\end{equation}

**v** (2,1) and **s** (-3,2)

\begin{equation} \vec{v} \cdot \vec{s} = (2 \cdot -3) + (1 \cdot 2) = -6 + 2 = -4\end{equation}


In [ ]:
v = np.array([2,1])
s = np.array([-3,2])
print(v @ s)
print(np.dot(v,s))
print(np.matmul(v,s))


-4
-4
-4


벡터의 내적은 다음과 같다. 이를 통해 두 벡터가 이루는 각 $\theta$ 를 알 수 있다.
$$ \vec{v} \cdot \vec{s} = \|\vec{v} \|\|\vec{s}\| \cos (\theta) $$ 

$$ \cos(\theta) = \frac{\vec{v} \cdot \vec{s}}{\|\vec{v} \|\|\vec{s}\|} $$

$$ \cos(\theta) = \frac{(2 \cdot-3) + (-3 \cdot 2)}{\sqrt{2^{2} + 1^{2}} \times \sqrt{-3^{2} + 2^{2}}} $$

$$\cos(\theta) = \frac{-4}{8.0622577483}$$

$$\cos(\theta) = -0.496138938357 $$

$$\theta \approx 119.74 $$

결국 두 벡터가 이루는 각을 통해 두 벡터의 유사도(같은 방향을 가리키는 정도)를 알 수 있다.

$0$도 일때는 두 벡터의 방향이 완전히 일치하며 내적은 최대 값이 된다.

$90$도 일때는 두 벡터가 직교인 상태이며 내적은 $0$이다.

$180$도 일때는 두 벡터의 방향이 반대이며 내적은 최소값이 된다.

따라서, 
$$
|\vec{x}\cdot\vec{y}| \leq \|\vec{x}\|\|\vec{y}\
$$
이다.

In [ ]:
import numpy as np

v = np.array([2,1])
s = np.array([-3,2])

vMag = np.linalg.norm(v)
sMag = np.linalg.norm(s)

cos = (v @ s) / (vMag * sMag)

theta = np.degrees(np.arccos(cos))

print(theta)

119.74488129694222


#### 외적
벡터의 외적은 새로운 벡터를 생성한다.벡터의 외적은 3차원 공간의 벡터들간의 이항연산의 일종이다.
\begin{equation}\vec{p} = \begin{bmatrix}2 \\ 3 \\ 1 \end{bmatrix}\;\; \vec{q} = \begin{bmatrix}1 \\ 2 \\ -2 \end{bmatrix}\end{equation}

\begin{equation}r_{1} = p_{2}q_{3} - p_{3}q_{2}\end{equation}
\begin{equation}r_{2} = p_{3}q_{1} - p_{1}q_{3}\end{equation}
\begin{equation}r_{3} = p_{1}q_{2} - p_{2}q_{1}\end{equation}

\begin{equation}\vec{r} = \vec{p} \times \vec{q} = \begin{bmatrix}(3 \cdot -2) - (1 \cdot 2) \\ (1 \cdot 1) - (2 \cdot -2) \\ (2 \cdot 2) - (3 \cdot 1) \end{bmatrix} = \begin{bmatrix}-6 - 2 \\ 1 - -4 \\ 4 - 3 \end{bmatrix} = \begin{bmatrix}-8 \\ 5 \\ 1 \end{bmatrix}\end{equation}



In [ ]:
p = np.array([2,3,1])
q = np.array([1,2,-2])
r = np.cross(p,q)
print(r)

[-8  5  1]


## Matrices(행렬)
행렬은 숫자를 직사각형 모양으로 배열해 놓은 것이다. 행렬은 행과 열로 이루어지며 특정 위치의 원소를 접근하기 위하여 행과 열의 인덱스를 사용한다.  넘파이에서는 np.array를 통해 벡터와 행렬을 모두 만들 수 있게 된다. 결국 행렬 속에는 벡터들이 들어 있으며 행 벡터, 열 벡터로 행과 열로 구분하여 지칭할 수 도 있다. 또한, 매트릭스의 기본 연산을 수행하기 쉽도록 np.matrix()를 지원한다.
\begin{equation}A = \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6
 \end{bmatrix}
\end{equation}


\begin{equation}A = \begin{bmatrix}
  a_{1,1} & a_{1,2} & a_{1,3} \\
  a_{2,1} & a_{2,2} & a_{2,3}
 \end{bmatrix}
\end{equation}



In [ ]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
print(A)
print(A.shape)
print(A.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


### 행렬의 합과 차
벡터와 마찬가지로 넘파이를 이용해서 합과 차는 벡터와 동일하다.
\begin{equation}\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}+ \begin{bmatrix}6 & 5 & 4 \\3 & 2 & 1\end{bmatrix} = \begin{bmatrix}7 & 7 & 7 \\7 & 7 & 7\end{bmatrix}\end{equation}


In [ ]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[6,5,4],
              [3,2,1]])
print(A + B)
print(A - B)

[[7 7 7]
 [7 7 7]]
[[-5 -3 -1]
 [ 1  3  5]]


### 전치 행렬
전치 행렬은 행과 열을 바꾸는 것이며 넘파이에서는 transpose() 함수 또는 .T로 연산을 할 수 있다.
\begin{equation}\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}^{T} = \begin{bmatrix}1 & 4\\2 & 5\\3 & 6 \end{bmatrix}\end{equation}

In [ ]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
print(np.transpose(A))
print(A.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


### 스칼라 곱
\begin{equation}2 \times \begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix} = \begin{bmatrix}2 & 4 & 6 \\8 & 10 & 12\end{bmatrix}\end{equation}


In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])
print(2 * A)

[[ 2  4  6]
 [ 8 10 12]]


### 행렬 곱
\begin{equation}\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix} \cdot \begin{bmatrix}9 & 8 \\ 7 & 6 \\ 5 & 4\end{bmatrix}\end{equation}


\begin{equation}(1,2,3) \cdot (9,7,5) = (1 \times 9) + (2 \times 7) + (3 \times 5) = 38\end{equation}

$$\cdots$$

\begin{equation}(4,5,6) \cdot (8,6,4) = (4 \times 8) + (5 \times 6) + (6 \times 4) = 86\end{equation}


\begin{equation}\begin{bmatrix}38 & 32\\101 & 86\end{bmatrix} \end{equation}


인공지능 분야에서 두 행렬의 곱셈은 np.dot() 함수를 많이 사용한다. 이 경우 dot 연산은 행렬vs행렬, 행렬vs벡터, 벡터vs벡터의 연산 모두를 지원한다. 

In [ ]:
# 1.행렬-행렬
A = np.array([[1,2,3]
               ,[4,5,6]])
B = np.array([[9,8],
               [7,6],
               [5,4]])
print(A.shape)
print(B.shape)
print(np.dot(A,B))
print(np.dot(A,B).shape)

(2, 3)
(3, 2)
[[ 38  32]
 [101  86]]
(2, 2)


In [ ]:
# 2.행렬-벡터
A = np.array([[1,2,3]
               ,[4,5,6]])
B = np.array([1,2,3])
print(A.shape)
print(B.shape)
print(np.dot(A,B))
print(np.dot(A,B).shape)

(2, 3)
(3,)
[14 32]
(2,)


In [ ]:
# 2.행렬-벡터
A = np.array([1,2,3])
B = np.array([1,2,3])
print(A.shape)
print(B.shape)
print(np.dot(A,B))
print(np.dot(A,B).shape)

(3,)
(3,)
14
()


np.array() 를 통해 행렬을 처리하는 것이 아닌 np.matrix를 통해서도 행렬의 연산을 수행할 수 있다.

In [ ]:
import numpy as np

##매트릭스로 선언
A = np.matrix([[1,2,3]
               ,[4,5,6]])
B = np.matrix([[9,8],
               [7,6],
               [5,4]])
print(type(A))
print(A * B)
print(np.dot(A,B))
print(B * A)
print(np.dot(B,A))


<class 'numpy.matrix'>
[[ 38  32]
 [101  86]]
[[ 38  32]
 [101  86]]
[[41 58 75]
 [31 44 57]
 [21 30 39]]
[[41 58 75]
 [31 44 57]
 [21 30 39]]


##랜덤
넘파이를 이용하여 랜덤하게 수를 발생시킬때는 ranom 함수를 사용한다. 신경망의 가중치 등을 초기화 할 때 랜덤하게 부여된 가중치를 이용하여 학습을 진행한다.
rand 함수는 0, 1 사이의 난수를 발생시키며 매개변수의 수 만큼 랜덤하게 수를 돌려준다. 다음 함수는 균등분포로 부터 랜덤하게 수를 추출하는 것이다.

In [ ]:
import numpy as np
print(np.random.rand(10))
print(np.random.rand(2,3))

[0.55951959 0.52398407 0.15219648 0.48591084 0.04385471 0.60272615
 0.15203438 0.81475878 0.71800598 0.62592359]
[[0.85617939 0.1875218  0.69608143]
 [0.44549532 0.74294399 0.53596572]]


물론 다양한 분포를 가정한 랜덤 넘버의 추출이 가능하다. 정규분포로 부터 랜덤한 수를 추출하기 위해서는 다음 함수를 호출한다.


In [ ]:
print(np.random.randn(5,5))

[[-0.96576045 -0.18717868 -1.66827065  1.68646347  0.29835643]
 [-0.7512397  -1.03596542  0.40029393  2.52101491  0.39646358]
 [ 0.39919167  1.83661896 -0.52983991 -1.32872733 -0.9488517 ]
 [-0.94847088  1.35959069  0.61553382  1.05219763 -0.20699843]
 [ 0.46930131 -0.57837469  0.05701029  2.16828757  0.34279705]]


## Indexing and Slicing
벡터의 색인과 슬라이싱은 파이썬의 리스트와 동일하다.


In [ ]:
x = np.array([2,4,6,8,10])
print(x[0])
print(x[4]) 

2
10


In [ ]:
x = np.random.rand(10)   
x1 = x[2:5]             
x2 = x[:4]              
x3 = x[7:]              
xlast = x[-1]           

print("x=      "+np.array_str(x,precision=3))
print("x[2:5]= "+np.array_str(x1,precision=3))
print("x[:4]=  "+np.array_str(x2,precision=3))
print("x[7:]=  "+np.array_str(x3,precision=3))
print("xlast=  {0:5.3f}".format(xlast))


x=      [0.522 0.468 0.637 0.932 0.487 0.251 0.933 0.712 0.225 0.713]
x[2:5]= [0.637 0.932 0.487]
x[:4]=  [0.522 0.468 0.637 0.932]
x[7:]=  [0.712 0.225 0.713]
xlast=  0.713


행렬의 색인과 슬라이싱 역시 동일하며 행렬의 색인과 슬라이싱은 머신러닝 분야에서 자주 사용되고 있다.

In [ ]:
x = np.arange(0,12)
print(type(x))
print(len(x))
print(x)

<class 'numpy.ndarray'>
12
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
y = np.reshape(x, (3,4))
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(y[:,0]) #첫 번째 열 추출

[0 4 8]


In [ ]:
print(y[:, 1:-1])

[[ 1  2]
 [ 5  6]
 [ 9 10]]


넘파이의 행렬은 다음과 같이 axis 특성을 갖고 있다. 이 축 정보를 통해 편리한 연산이 가능하다.
<p align="center"><img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="70%" height="70%"></p>




y 행렬은 다음과 같이 3행 4열 행렬이며 axis=0은 열 단위로, axis=1은 행단위로 생각할 수 있다.

In [ ]:
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


따라서 다음 코드는 위 행렬의 열 단위 합을 출력한다.

In [ ]:
print(np.sum(y, axis = 0))

[12 15 18 21]


또한, 다음 코드는 위 행렬의 행 단위 합을 출력한다.


In [ ]:
print(np.sum(y, axis = 1))

[ 6 22 38]


In [ ]:
print(np.sum(y))

66


# 결론
이상으로 간단하게 넘파이에 대한 소개를 마무리 한다. 넘파이는 머신러닝에서 필수적으로 사용되므로 넘파이에 대한 이해를 바탕으로 보다 깊은 학습을 수행할 수 있을 것이다.